# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_type', models.CharField(choices=[('tested', 'Tested 1RM'), ('estimated', 'Estimated 1RM'), ('rep_max', 'Rep max'), ('training', 'Training max'), ('coach', 'Coach-assigned max')], max_length=12)),
                ('weight_lb', models.DecimalField(decimal_places=1, max_digits=6)),
                ('reps', models.PositiveSmallIntegerField(default=1, help_text='Reps performed at that weight (1 for a true 1RM).')),
                ('estimated_1rm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('tested_1rm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('date', models.DateField(db_index=True)),
                ('bodyweight_at_time_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maxes_entered', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lift_maxes', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lift_maxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'lift maxes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('weight', 'Heaviest weight'), ('e1rm', 'Best estimated 1RM'), ('reps', 'Most reps at a weight'), ('tested', 'Tested max')], max_length=10)),
                ('value', models.DecimalField(decimal_places=1, max_digits=7)),
                ('weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_records', to='exercises.exercise')),
                ('set_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='workouts.setlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
