# Generated by Django 5.2.16 on 2026-07-14 09:09

import core.services.storage
import django.db.models.deletion
import profiles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, storage=core.services.storage.get_private_storage, upload_to=profiles.models.profile_photo_path)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex_for_calculations', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Used only for energy-expenditure and body-fat equations.', max_length=10)),
                ('height_inches', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('current_weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('goal_weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('training_goal', models.CharField(choices=[('cut', 'Cut'), ('recomp', 'Body recomposition'), ('maintain', 'Maintain'), ('lean_bulk', 'Lean bulk'), ('performance', 'Performance'), ('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('general', 'General fitness')], default='general', max_length=20)),
                ('training_experience', models.CharField(choices=[('beginner', 'Beginner (<1 year)'), ('novice', 'Novice (1–2 years)'), ('intermediate', 'Intermediate (2–5 years)'), ('advanced', 'Advanced (5+ years)')], default='beginner', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('very', 'Very active'), ('extreme', 'Extremely active')], default='light', max_length=20)),
                ('occupation_activity', models.CharField(choices=[('seated', 'Mostly seated'), ('mixed', 'Mixed sitting/standing'), ('standing', 'On feet most of the day'), ('physical', 'Physically demanding')], default='seated', max_length=20)),
                ('weekly_lifting_days', models.PositiveSmallIntegerField(default=3)),
                ('weekly_running_days', models.PositiveSmallIntegerField(default=0)),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('general_notes', models.TextField(blank=True, help_text='Coach/administrator notes. Not shown to the client.')),
                ('movement_limitations', models.TextField(blank=True)),
                ('injury_cautions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_profiles', to=settings.AUTH_USER_MODEL)),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_athletes', to='programs.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('bodyweight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulders', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_arm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_forearm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_forearm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_calf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_calf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_body_fat', models.DecimalField(blank=True, decimal_places=1, help_text='Rough estimate (%). May be manually overridden by the coach.', max_digits=4, null=True)),
                ('measurement_method', models.CharField(choices=[('tape', 'Tape measure'), ('navy', 'Navy circumference estimate'), ('caliper', 'Calipers'), ('scale', 'Smart scale / BIA'), ('dexa', 'DEXA scan'), ('visual', 'Visual estimate'), ('other', 'Other')], default='tape', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_entered', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
