# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('recovery', 'Recovery'), ('general_health', 'General health'), ('protein', 'Protein'), ('hydration', 'Hydration'), ('vitamin_mineral', 'Vitamin / mineral'), ('other', 'Other')], default='other', max_length=20)),
                ('purpose', models.TextField()),
                ('evidence_summary', models.TextField(blank=True)),
                ('default_dose', models.CharField(blank=True, max_length=100)),
                ('dose_unit', models.CharField(blank=True, max_length=30)),
                ('timing', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('bodyweight_based', models.BooleanField(default=False, help_text='Dose commonly scaled to bodyweight (e.g. caffeine).')),
                ('maximum_recommended_amount', models.CharField(blank=True, max_length=200)),
                ('warnings', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('educational_disclaimer', models.TextField(default='Educational information only — not medical advice, and not a treatment for any disease. Talk with a qualified healthcare professional before starting any supplement, especially if you take medication or have a medical condition.')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSupplementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_dose', models.CharField(max_length=100)),
                ('dose_unit', models.CharField(blank=True, max_length=30)),
                ('timing', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement_recommendations_entered', to=settings.AUTH_USER_MODEL)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='supplements.supplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', 'supplement__name'],
            },
        ),
    ]
