# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('session_type', models.CharField(choices=[('lifting', 'Lifting'), ('running', 'Running'), ('mobility', 'Mobility'), ('rest', 'Rest day'), ('testing', 'Testing / max day'), ('measurement', 'Measurement'), ('checkin', 'Check-in')], default='lifting', max_length=15)),
                ('title', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('missed', 'Missed')], default='scheduled', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sessions', to='programs.workoutdaytemplate')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
