# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default rules', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('protein_g_per_lb', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('protein_g_per_lb_cut', models.DecimalField(decimal_places=2, default=1.0, help_text='Higher protein while cutting / recomping.', max_digits=4)),
                ('fat_percent_calories', models.DecimalField(decimal_places=1, default=25, max_digits=4)),
                ('fat_minimum_g_per_lb', models.DecimalField(decimal_places=2, default=0.25, max_digits=4)),
                ('fiber_g_per_1000_kcal', models.DecimalField(decimal_places=1, default=14, max_digits=4)),
                ('water_oz_per_lb', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('cut_max_weekly_loss_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Weekly loss above this % of bodyweight is flagged.', max_digits=4)),
                ('recomp_deficit_percent', models.DecimalField(decimal_places=1, default=5, max_digits=4)),
                ('performance_surplus_kcal', models.PositiveSmallIntegerField(default=150)),
                ('kcal_per_lb_weekly_change', models.PositiveSmallIntegerField(default=500, help_text='Daily kcal delta per 1 lb/week of weight change.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('goal', models.CharField(blank=True, max_length=20)),
                ('method', models.CharField(choices=[('mifflin', 'Mifflin-St Jeor'), ('katch', 'Katch-McArdle'), ('manual', 'Manual')], default='mifflin', max_length=10)),
                ('maintenance_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_weekly_change_lb', models.DecimalField(blank=True, decimal_places=2, help_text='Negative = loss, positive = gain.', max_digits=4, null=True)),
                ('calculated_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_fat_g', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_fiber_g', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_water_oz', models.PositiveIntegerField(blank=True, null=True)),
                ('final_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('final_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('final_carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('final_fat_g', models.PositiveIntegerField(blank=True, null=True)),
                ('final_fiber_g', models.PositiveIntegerField(blank=True, null=True)),
                ('final_water_oz', models.PositiveIntegerField(blank=True, null=True)),
                ('sodium_guidance', models.CharField(blank=True, max_length=300)),
                ('pre_workout_suggestion', models.TextField(blank=True)),
                ('post_workout_suggestion', models.TextField(blank=True)),
                ('example_meals', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_targets_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_met', models.BooleanField(default=False)),
                ('protein_met', models.BooleanField(default=False)),
                ('water_met', models.BooleanField(default=False)),
                ('fiber_met', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_checkin_per_day')],
            },
        ),
    ]
