# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('lower_back', 'Lower back'), ('full_body', 'Full body'), ('other', 'Other')], max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list, help_text='List of muscle keys, e.g. ["triceps"].')),
                ('movement_pattern', models.CharField(choices=[('horizontal_push', 'Horizontal push'), ('vertical_push', 'Vertical push'), ('horizontal_pull', 'Horizontal pull'), ('vertical_pull', 'Vertical pull'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('lunge', 'Lunge'), ('carry', 'Carry'), ('rotation', 'Rotation'), ('locomotion', 'Locomotion'), ('isolation_pattern', 'Isolation'), ('other', 'Other')], default='other', max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('band', 'Band'), ('sled', 'Sled'), ('landmine', 'Landmine'), ('other', 'Other')], default='barbell', max_length=20)),
                ('exercise_category', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('power', 'Power'), ('plyometric', 'Plyometric'), ('running', 'Running'), ('conditioning', 'Conditioning'), ('mobility', 'Mobility'), ('core', 'Core'), ('rehab', 'Rehabilitation'), ('warmup', 'Warm-up')], default='strength', max_length=20)),
                ('unilateral', models.BooleanField(default=False)),
                ('is_compound', models.BooleanField(default=True, verbose_name='compound (vs isolation)')),
                ('training_focus', models.CharField(choices=[('strength', 'Strength'), ('power', 'Power'), ('hypertrophy', 'Hypertrophy'), ('mixed', 'Mixed')], default='mixed', help_text='Strength / power / hypertrophy classification.', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('coaching_cues', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('default_rest_seconds', models.PositiveSmallIntegerField(default=120)),
                ('default_video_url', models.URLField(blank=True)),
                ('public', models.BooleanField(default=True, help_text='Visible to all athletes in the library.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_created', to=settings.AUTH_USER_MODEL)),
                ('substitutions', models.ManyToManyField(blank=True, to='exercises.exercise')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
