# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('exercises', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('partial', 'Partially completed')], default='in_progress', max_length=12)),
                ('energy', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('soreness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('motivation', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pain_today', models.BooleanField(default=False)),
                ('session_difficulty', models.PositiveSmallIntegerField(blank=True, help_text='1 easy – 10 maximal', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pump_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('had_pain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='programs.program')),
                ('scheduled_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='calendar_app.scheduledsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='programs.workoutdaytemplate')),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body_location', models.CharField(max_length=100)),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pain_type', models.CharField(choices=[('sharp', 'Sharp'), ('aching', 'Aching'), ('burning', 'Burning'), ('numbness', 'Numbness'), ('tingling', 'Tingling'), ('weakness', 'Weakness'), ('instability', 'Instability'), ('other', 'Other')], default='aching', max_length=15)),
                ('affected_performance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by_coach', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_reports', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_reports', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('is_warmup', models.BooleanField(default=False)),
                ('is_extra', models.BooleanField(default=False, help_text='Added beyond the prescription.')),
                ('weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rir', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('distance_yards', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('substitution_request', models.CharField(blank=True, help_text='Client may request a substitution; the coach decides.', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_logs', to='exercises.exercise')),
                ('workout_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_logs', to='programs.workoutexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['exercise_id', 'set_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'workout_exercise', 'exercise', 'set_number'), name='unique_set_per_exercise_per_session')],
            },
        ),
    ]
