# Generated by Django 5.2.16 on 2026-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('programs', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='setlog',
            name='unique_set_per_exercise_per_session',
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.UniqueConstraint(fields=('session', 'workout_exercise', 'exercise', 'set_number', 'is_warmup'), name='unique_set_per_exercise_per_session'),
        ),
    ]
