# Generated by Django 5.2.16 on 2026-07-14 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('main_goal', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('power', 'Power'), ('fat_loss', 'Fat loss'), ('conditioning', 'Conditioning'), ('general', 'General fitness')], default='general', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('number_of_weeks', models.PositiveSmallIntegerField(default=4)),
                ('progression_enabled', models.BooleanField(default=True)),
                ('coach_notes', models.TextField(blank=True, help_text='Never shown to the client.')),
                ('client_visible_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_assigned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Coach/administrator who built it.', on_delete=django.db.models.deletion.CASCADE, related_name='programs_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('deload', models.BooleanField(default=False)),
                ('testing_week', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.program')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('default_weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday. Used when generating the calendar.', null=True)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warmup_notes', models.TextField(blank=True)),
                ('workout_notes', models.TextField(blank=True)),
                ('cooldown_notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek')),
            ],
            options={
                'ordering': ['order', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('superset_group', models.CharField(blank=True, help_text='Exercises sharing a letter are a superset.', max_length=5)),
                ('warmup_sets', models.PositiveSmallIntegerField(default=0)),
                ('target_sets', models.PositiveSmallIntegerField(default=3)),
                ('target_rep_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_rep_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_reps_text', models.CharField(blank=True, help_text='Free-form target, e.g. AMRAP, 30 seconds, 20-40 yd.', max_length=40)),
                ('target_weight_lb', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('target_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Percent of training max.', max_digits=5, null=True)),
                ('target_rir', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempo', models.CharField(blank=True, max_length=20)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progression_method', models.CharField(choices=[('double', 'Double progression (reps then weight)'), ('fixed_load', 'Fixed load increase after success'), ('percentage', 'Percentage of training max'), ('rep', 'Rep progression at constant weight'), ('rir_rpe', 'RIR/RPE-gated weight increase'), ('manual', 'Manual (coach decides)'), ('performance', 'Performance-based recommendation')], default='double', max_length=20)),
                ('weight_increment_lb', models.DecimalField(decimal_places=1, default=5, help_text='Increment used by progression recommendations.', max_digits=5)),
                ('client_visible_notes', models.TextField(blank=True)),
                ('private_coach_notes', models.TextField(blank=True)),
                ('optional', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='exercises.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.workoutdaytemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='programweek',
            constraint=models.UniqueConstraint(fields=('program', 'week_number'), name='unique_week_per_program'),
        ),
    ]
