# Generated by Django 5.2.16 on 2026-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='set_weight_targets_lb',
            field=models.JSONField(blank=True, default=list, help_text='Optional working-set weights in order, e.g. [290, 305].'),
        ),
    ]
